---
engines:
  duplication:
    enabled: false
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    channel: "eslint-3"
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
exclude_paths:
- dist/
- test/
- build/
